general:
  description: See original run
  working_dir: ${STOREDIR}/data_hamlet/CF4gp/${DIR}/
  load_working_dir: True
  libraries_dirs: ${CODEDIR}/hamlet/                                                    
  copy_data: True
  copy_libraries: False
    
logging:
    verbosity: 3                                              
    debug_classes: &debug_classes ['ClustersAnalysis', 'FieldsAnalysis']
    highlights: *debug_classes

strategy:
    strategy: StrategyLoadAnalyze

    load:
      # name_run: &name_run warmup
      # kernel: &kernel KernelDualAveragingNUTS                 
      name_run: &name_run main
      kernel: &kernel KernelNUTS                 

    analyze:
      name_run: *name_run
      kernel: *kernel 
      subsample: [0, 500, 25]
      # subsample: [0, 1, 1]

data:
  features:
    path: ${STOREDIR}/catalogs/features_HAMLET.txt
    prepend_name: True
    filters:
      names:
        # - [name, ['Virgo', 'Fornax', 'Coma', 'Hydra', 'Norma', 'Perseus',  'Ophiuchus', 'Hercules']]
        - [name, []]

analyses:

  InitialConditions:
    save_level: 1
    plot_level: 0
    log2_refine: 2
    update_conf_kwargs:
      a_start: 0.015625

    # refine_seeds: 
      # - [0, 1, 3, 4, 5]
    # keep_reals: "0:100:10"

  FieldsAnalysis: 
    plot_level: 2
    save_level: 0
    plot_points: ${STOREDIR}/catalogs/CF4corr_full.npz
    plot_fields: ['dens', 'vr']
    save_fields: ['dens']
    _plot_exts: ['jpg']
  
  # ClustersAnalysis:
  #   plot_level: 1
  #   save_level: 0
  #


