analyses:
  TestAnalysis:
    plot_level: 1
    save_level: 1
data:
  direction: null
  dist_mod: null
  err_dist_mod: null
  err_z_tot: null
  example_mask: null
  type: null
  z_tot: null
general:
  copy_data: true
  copy_libraries: false
  description: This is a test model of banana
  libraries_dirs:
  - ./
  load_working_dir: false
  working_dir: ./output_test_dir
logging:
  debug_classes: &id001
  - Redshifts
  highlights: *id001
  verbosity: 2
modules:
  LikelihoodDistanceModuli: null
  LikelihoodRedshifts: null
  PriorDistances: null
  PriorVelocities: null
parameters:
  cosmology:
    Omega_m: 0.3
    h0: 0.746
  sigma_v: 300.0
strategy:
  run_debug:
    debug_classes: *id001
    run: false
  run_kernel_main:
    kernel: KernelNUTS
    nuts_kwargs:
      max_tree_depth: 8
    sample_chain_kwargs:
      num_results: 100
      num_steps_between_results: 1
  run_kernel_warmup:
    dual_avg_kwargs:
      num_adaptation_steps: 80
    kernel: KernelDualAveragingNUTS
    nuts_kwargs:
      max_tree_depth: 8
    sample_chain_kwargs:
      num_results: 100
      num_steps_between_results: 1
  strategy: StrategyFullRun
variables:
  Distances: null
  Velocities: null
